###
POST  http://localhost:4000/login
Content-Type: application/json

{
  "login":"vinos",
  "password":"123456"
}
###
GET http://localhost:4000/boards/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6ImFkbWluIiwiX2lkIjoiNWY5OTcxNjJmNTA0NjgzNzY4Yjk5NGY1IiwiaWF0IjoxNjAzODkxNTYyLCJleHAiOjE2MDM4OTUxNjJ9.0t2H2Nn3_n-4pioCcIvmveNBOZJ0PermAFzfp_i45_g
###
GET http://localhost:4000/boards/undefined
###
POST http://localhost:4000/users/
Content-Type: application/json

{
  "name":"admin",
  "login":"admin",
  "password":"T35t_P@55w22330rd"
}
###
PUT http://localhost:4000/users/1fdadac4-df69-459a-a80c-63f8dc753c4b
Content-Type: application/json

{
  "name":"TEST_Pasha2233",
  "login":"test_razinkov2332",
  "password":"T35t_P@55w22330rd"
}
### Get users by ID
GET http://localhost:4000/users/28861758-85cf-4554-b292-fa232142fcae1
### Get boards by id
GET http://localhost:4000/boards/5f93d5ddb6fab66d0c0e83c5/tasks
### Get All users
GET http://localhost:4000/tasks/dgdfgfd7gf7g65x6g58x
### Get All users
GET  http://localhost:4000/boards/a8ae6337-ad6b-442c-bad9-101b264410c9


### Get All users
GET http://localhost:4000/boards/be444f5c-7d86-455f-92ee-ab99eb1b0a84/tasks

###

# curl -X POST "http://localhost:4000/boards/46259cdc-fd02-4c4f-b818-9c512e6e1a8f/tasks" -H "accept: application/json" -H "Content-Type: application/json" -d "{\"title\":\"string\",\"order\":0,\"description\":\"string\",\"userId\":\"string\",\"boardId\":\"string\",\"columnId\":\"string\"}"
POST http://localhost:4000/boards/
Content-Type: application/json

{
  "title": "testTask",
  "order": 0,
  "description": "testovaya",
  "userId": "string",
  "boardId": "string",
  "columnId": "string"
}

###
DELETE http://localhost:3400/users/3e18df37-4d9d-4fc1-b84b-26c92eb3e9b8